### ISSUE TITLE
[Error]: Honkai: Star Rail Cache and Repair returns Invalid URI Errors

### ISSUE THREAD

**Issue by Jhanks93** [CollapseLauncher/Collapse#310]
### Affected Version

1.71.16

### Bug Behavior

An error occurs when trying to Repair Game or Refresh Cache, Honkai: Star Rail

### Expected Behavior

The Launcher allows Game Repair, to be able to download the missing HRS files

### Steps to reproduce

1.Run launcher.
2.Switch to HRS
3.Repair Game
4.Quick Check

### Screenshot(s)

![error](https://github.com/CollapseLauncher/Collapse/assets/144684739/1c8532d4-ad06-4b39-b48b-21f3ea11036e)

### Additional Information

System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength)
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.ParseArchive()
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRDispatcherInfo.Initialize(CancellationToken threadToken, String persistentDirectory, String regionName)
   at Hi3Helper.EncTool.Parser.AssetMetadata.SRMetadata.Initialize(CancellationToken threadToken, String regionName, String persistentDirectory, Boolean forceInitialize)
   at CollapseLauncher.StarRailRepair.Fetch(List`1 assetIndex, CancellationToken token)
   at CollapseLauncher.StarRailRepair.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailRepair.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

**Comment by takutosama** [comment]
have the same problem here, even after update

**Comment by bagusnl** [comment]
Seems like the dispatch for HSR has changed, will try to investigate a little bit once I'm free. Thank you for reporting the issue!

**Comment by bagusnl** [comment]
Update: it seems that the dispatch is throwing `client version not match` and `region is undergoing maintenance`
Can someone confirm that the game is currently cannot be opened?

**Comment by Jhanks93** [comment]
The error only occurs when checking the data, but it does allow the game to be launched

**Comment by bagusnl** [comment]
Ok, I have found the issue. Will push a metadata update soon

**Comment by Jhanks93** [comment]
OK thanks

**Comment by bagusnl** [comment]
Metadata is pushed, please restart your launcher. If you did not get a "Launcher Metadata Update is Available" notification, please press "Clear Metadata and Restart" button in Collapse settings!

Thank you for reporting the issue and we are sorry for the inconvenience that's caused. Feel free to reopen this issue if problem persist

<3

**Comment by Jhanks93** [comment]
I just updated the metadata, thanks for your quick response to the problem
