### ISSUE TITLE
[Bug]: Star Rail not opening after update

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#351]
### Affected Version

Collapse 1.72.12-Pre

### Bug Behavior

Cache Update report:

System.IO.InvalidDataException: The dispatcher response is invalid! Please open an issue to our GitHub page to report this issue.
   at CollapseLauncher.StarRailCache.Fetch(CancellationToken token)
   at CollapseLauncher.StarRailCache.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailCache.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.CachesPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

### Expected Behavior

Should open the game.

### Steps to reproduce

1. Reboot the launcher
2. Full Game repair

**Comment by muscularcandy67** [comment]
Hello, currently HSR Cache Update and Game Repair don't work. Some stuff changed and it will take a while to get them properly fixed. Kindly wait for a fix. If the game doesn't launch try doing the steps suggested [here](https://github.com/CollapseLauncher/Collapse/issues/350)

**Comment by Caelum008** [comment]
it worked when I updated the game through the OG launcher. although it redownloaded everything. thank you for the help!

**Comment by bagusnl** [comment]
Fixed in 1.72.14

Thank you for submitting bug report for Collapse!
