### ISSUE TITLE
[Bug]: "Caches Update" not working for Honkai: Star Rail (Global)

### ISSUE THREAD

**Issue by Loup-1234** [CollapseLauncher/Collapse#396]
### Affected Version

Collapse 1.72.17

### Bug Behavior

System.IO.InvalidDataException: The dispatcher response is invalid! Please open an issue to our GitHub page to report this issue.
   at CollapseLauncher.StarRailCache.Fetch(CancellationToken token)
   at CollapseLauncher.StarRailCache.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`2.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailCache.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.CachesPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

### Expected Behavior

Maybe there is a new Token released by Hoyoverse.

### Steps to reproduce

1. Open Collapse
2. Select Honkai: Star Rail (Global)
3. Go to "Caches Update"
4. Click on "Quick Check" or "Full check"

**Comment by bagusnl** [comment]
Heya! Thank you for submitting bug report for Collapse!

Sorry for not updating you all with this issue but this is expected as SR update always breaks repair and cache update. This has been fixed and just waiting for verification for the next build update

Sorry for the inconvenience!

**Comment by bagusnl** [comment]
Closing as fix has been pushed~
