### ISSUE TITLE
[Bug]: Game Install Unhandled Error on Bad Install Location

### ISSUE THREAD

**Issue by TheOppaiDragon** [CollapseLauncher/Collapse#441]
### Affected Version

1.72.16

### Bug Behavior

When genshin finish check file give me the error

### Expected Behavior

It should not have given me this error simply

### Steps to reproduce

1. Open Launcher
2. Choose Genshin
3. Download Genshin 
4. Wait finish check file
5. Error got

### Additional Information

```
System.UnauthorizedAccessException: Access to the path 'D:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1, String)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.TryUnassignReadOnlyFiles()
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<StartPackageInstallationInner>b__60_0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallationInner()
   at CollapseLauncher.InstallManager.Genshin.GenshinInstall.StartPackageInstallationInner()
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallation()
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e)
```
[log-2024-03-26-sta1.72.16-id1.log](https://github.com/CollapseLauncher/Collapse/files/14751008/log-2024-03-26-sta1.72.16-id1.log)
[DxDiag.txt](https://github.com/CollapseLauncher/Collapse/files/14751010/DxDiag.txt)

**Comment by bagusnl** [comment]
Heyyo~

Its been an ongoing issue with this and still unsure why, but try restarting your system and see if it works

**Comment by TheOppaiDragon** [comment]
It did not work because the zip file download was on the main hard disk without a folder. Putting the zips into Genshin's folder worked

**Comment by bagusnl** [comment]
Ah i see
We'll update our game installation folder sanitazion mechanism to prevent user to do this

**Comment by bagusnl** [comment]
Hi, I have put a method to prevent user to put installation folder in the root of a drive (like 2 minor preview version before but i forgor to update this issue ticket :tehee:).

Thanks for supporting Collapse!
