### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rallus-Zenturi** [CollapseLauncher/Collapse#499]
### Affected Version

1.80.11

### Bug Behavior

Issue on updating HSR to V2.3

### Expected Behavior

idk updaate the game

### Steps to reproduce

Clicked on update Game 

### Additional Information

System.IO.IOException: IO_SharingViolation_File, H:\Games\Star Rail\Games\UnityCrashHandler64.exe
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.ExtractUsingNativeZipWorker(IEnumerable`1 entriesIndex, List`1 entries, CancellationToken cancellationToken)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<>c__DisplayClass93_0.<<ExtractUsingNativeZip>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.ExtractUsingNativeZip(GameInstallPackage asset)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallationInner(List`1 gamePackage, Boolean isOnlyInstallPackage, Boolean doNotDeleteZipExplicit)
   at CollapseLauncher.InstallManager.StarRail.StarRailInstall.StartPackageInstallationInner(List`1 gamePackage, Boolean isOnlyInstallPackage, Boolean doNotDeleteZipExplicit)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallation()
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

**Comment by bagusnl** [comment]
Restart windows and do better bug report next time
