### ISSUE TITLE
[Bug]: error verifying pre-update files

### ISSUE THREAD

**Issue by Jhanks93** [CollapseLauncher/Collapse#500]
### Affected Version

1.80.11

### Bug Behavior

After verifying the pre-download package the error appears

### Expected Behavior

auto_awesome
Quizás quisiste decir: deberia haber verificado el archivo de audio y comenzar a desempaquetar la actualizacion
88 / 5.000
You should have verified the audio file and started unpacking the update.

### Steps to reproduce

1. Run Collapse
2. Update the game

### Screenshot(s)

![Anotación 2024-06-18 202753](https://github.com/CollapseLauncher/Collapse/assets/144684739/c9cba250-1ccf-487e-9d2e-874bc20712c3)

### Additional Information

System.Runtime.InteropServices.COMException (0x8001010E)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32)
   at Microsoft.UI.Xaml.Controls.ContentDialog._IContentDialogFactory.CreateInstance(Object, IntPtr& )
   at Microsoft.UI.Xaml.Controls.ContentDialog..ctor()
   at CollapseLauncher.CustomControls.ContentDialogCollapse..ctor(ContentDialogTheme theme)
   at CollapseLauncher.Dialogs.SimpleDialogs.SpawnDialog(String title, Object content, UIElement Content, String closeText, String primaryText, String secondaryText, ContentDialogButton defaultButton, ContentDialogTheme dialogTheme)
   at CollapseLauncher.Dialogs.SimpleDialogs.Dialog_GameInstallationFileCorrupt(UIElement Content, String sourceHash, String downloadedHash)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.RunPackageVerificationRoutine(GameInstallPackage asset, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageVerification(List`1 gamePackage)
   at CollapseLauncher.InstallManager.StarRail.StarRailInstall.StartPackageVerification(List`1 gamePackage)
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

**Comment by neon-nyan** [comment]
Hi @Jhanks93,
We have noticed a bug within the ``ContentDialog`` component, causing the launcher to throw an error while trying to spawn a dialog menu. A fix for this will be shipped in the next hotfix, hopefully soon.

**Comment by neon-nyan** [comment]
Fixed as per v1.80.12 hotfix
