### ISSUE TITLE
[Bug]: Locale code error when updating Genshin Impact

### ISSUE THREAD

**Issue by Devyatyi9** [CollapseLauncher/Collapse#503]
### Affected Version

1.80.11

### Bug Behavior

Error after press "Update game" button
<details><summary>The error</summary>

```
System.Collections.Generic.KeyNotFoundException: Locale code: Japanese is not supported!
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.GetLanguageStringByLocaleCode(String localeCode)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.AddAdditionalVODiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)
```

</details>

### Expected Behavior

should have started updating the game

### Steps to reproduce

1. Open launcher
2. Press "Update game"

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/5161472/dc0ca4e2-d820-428b-804d-4d1953067f97)

### Additional Information

[DxDiag.txt](https://github.com/user-attachments/files/15904002/DxDiag.txt)
[logs.zip](https://github.com/user-attachments/files/15904027/logs.zip)

**Comment by neon-nyan** [comment]
Hi @Devyatyi9,
Thank you for noticing. We just pushed a commit to fix this issue and ship it in the next hotfix update

**Comment by Devyatyi9** [comment]
@neon-nyan I updated to the new version, but this error appeared, then the window closed and reopened.

<details><summary>Log</summary>

```
System.Exception: Couldn't acquire lock, is another instance running?
   at Squirrel.SingleGlobalInstance..ctor(String, TimeSpan)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__41_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at Squirrel.UpdateManager.CheckForUpdate(Boolean , Action`1 , UpdaterIntention )
   at CollapseLauncher.Updater.StartCheck()
   at CollapseLauncher.Pages.UpdatePage.GetSquirrelUpdate()
   at CollapseLauncher.Pages.UpdatePage._StartUpdateRoutine()
   at CollapseLauncher.Pages.UpdatePage.StartUpdateRoutine()
```

</details>

**Comment by neon-nyan** [comment]
Hi @Devyatyi9,
You can ignore the exception there and it should be fine. Just make sure that you are successfully updated your launcher to the latest version (1.80.12)
