### ISSUE TITLE
[Bug]: error when trying to extract files after verification 

### ISSUE THREAD

**Issue by mewlysia** [CollapseLauncher/Collapse#508]
### Affected Version

1.80.12 

### Bug Behavior

after the downloaded files are done verifying, it tells me that one of the downloaded files is corrupted and when i try to extract it anyway the error pops up

### Expected Behavior

it should have let me extract the files, and then repair the corrupted file individually after 

### Steps to reproduce

1. verify the files
2. after it fails and tells me one of the files is corrupted, click extract anyway

### Screenshot(s)

![imagen](https://github.com/CollapseLauncher/Collapse/assets/173558001/f1031292-2a08-48df-b83d-4c9ab1f41cff)

### Additional Information

System.Runtime.InteropServices.COMException (0x8001010E): La aplicación llamó a una interfaz que se aplanó para un diferente subproceso. (0x8001010E (RPC_E_WRONG_THREAD))
   at WinRT.BaseActivationFactory._ActivateInstance[I]()
   at Microsoft.UI.Xaml.Controls.TextBlock..ctor()
   at CollapseLauncher.Dialogs.SimpleDialogs.Dialog_GameInstallCorruptedDataAnyway(UIElement Content, String fileName, Int64 fileSize)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.RunPackageVerificationRoutine(GameInstallPackage asset, CancellationToken token)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageVerification(List`1 gamePackage)
   at CollapseLauncher.InstallManager.StarRail.StarRailInstall.StartPackageVerification(List`1 gamePackage)
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

is there a way to fix this without having to redownload it all again? this is my 2nd redownload and i dont wanna do it for a 3rd time as it takes me over 20 hours...

**Comment by bagusnl** [comment]
Try running Collapse build from this link https://nightly.link/CollapseLauncher/Collapse/actions/runs/9635303324


Just extract and run CollapseLauncher.exe
Then try again

**Comment by mewlysia** [comment]
> Try running Collapse build from this link https://nightly.link/CollapseLauncher/Collapse/actions/runs/9635303324

i did it and i was able to get past verifying into extracting the files but then while extracting this error pops up: 

SharpCompress.Compressors.Deflate.ZlibException: Bad state (oversubscribed dynamic bit lengths tree)
   at SharpCompress.Compressors.Deflate.InflateManager.Inflate(FlushType)
   at SharpCompress.Compressors.Deflate.ZlibBaseStream.Read(Byte[], Int32, Int32)
   at System.IO.Stream.<>c.<BeginReadInternal>b__38_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.ExtractUsingNativeZipWorker(IEnumerable`1 entriesIndex, List`1 entries, CancellationToken cancellationToken)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<>c__DisplayClass93_0.<<ExtractUsingNativeZip>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.ExtractUsingNativeZip(GameInstallPackage asset)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallationInner(List`1 gamePackage, Boolean isOnlyInstallPackage, Boolean doNotDeleteZipExplicit)
   at CollapseLauncher.InstallManager.StarRail.StarRailInstall.StartPackageInstallationInner(List`1 gamePackage, Boolean isOnlyInstallPackage, Boolean doNotDeleteZipExplicit)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageInstallation()
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

> Try running Collapse build from this link https://nightly.link/CollapseLauncher/Collapse/actions/runs/9635303324

**Comment by bagusnl** [comment]
There is not much one can do if the downloaded zip is corrupted so much that the extraction library cannot try to extract it anyway, sorry.

Please retry to download the file once again with lower download thread count or use download manager like FDM if you have a really bad internet connection (zip link that needs to be downloaded is there on the console)
