### ISSUE TITLE
[Bug]: The launcher did not create a subfolder for ZZZ 

### ISSUE THREAD

**Issue by Devyatyi9** [CollapseLauncher/Collapse#520]
### Affected Version

1.80.14

### Bug Behavior

```
System.IO.IOException: UnauthorizedAccess_IODenied_Path, \\?\F:\Games\Honkai Impact 3rd glb\AssMap
   at System.IO.FileSystem.RemoveDirectoryRecursive(String, WIN32_FIND_DATA&, Boolean)
   at System.IO.FileSystem.RemoveDirectory(String, Boolean)
   at System.IO.DirectoryInfo.Delete(Boolean)
   at CollapseLauncher.FileMigrationProcess.MoveDirectory(FileMigrationProcessUIRef uiRef)
   at CollapseLauncher.FileMigrationProcess.StartRoutineInner(FileMigrationProcessUIRef uiRef)
   at CollapseLauncher.FileMigrationProcess.StartRoutine()
   at CollapseLauncher.FileMigrationProcess.StartRoutine()
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.PerformMigrationOption(String pathIfUseExistingSelected, MigrateFromLauncherType launcherType, Boolean isMoveOperation)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.MoveGameLocation()
   at CollapseLauncher.Pages.HomePage.MoveGameLocationButton_Click(Object sender, RoutedEventArgs e)
```

### Expected Behavior

When I selected the path to install ZZZ, the launcher did not create a subfolder for the game as I expected. Then I decided to use the function of transferring files to another folder, after which the launcher began to transfer all the folders and files that were there (F:\Games)

### Steps to reproduce

1. Select the ZZZ installation path, for example D:\Games
2. Click on the button in the launcher to transfer game files and specify another folder on the same disk

**Comment by bagusnl** [comment]
This is expected behavior as even the locate game will only accept a directory on the root of folder you given to it. To separate it, move the files manually.

Here is the file for HI3
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/7d7306b2-0322-4850-a156-72b8a53395ef)


Here is the files for ZZZ
![image](https://github.com/CollapseLauncher/Collapse/assets/28079733/dee20490-2ec0-4d14-9cc5-8e0cd4801690)

Once you separate them, the most likely that would fully survive is the ZZZ as you got it in the last, you'll need to do a full repair on Hi3 to get it working again
