### ISSUE TITLE
[Bug]: Unable to Migrate ZZZ to Collapse

### ISSUE THREAD

**Issue by Bloo-561** [CollapseLauncher/Collapse#531]
### Affected Version

Collapse 1.80.15

### Bug Behavior

When Migrating ZZZ's folder to Collapse it does not change anything and all it does is return to the install button.

### Expected Behavior

Expected is the migration to complete and being able to start the game via the launcher

### Steps to reproduce

1. Install/Locate Game
2. Use Current Directory
3. Yes, Migrate it

### Screenshot(s)

![image](https://github.com/CollapseLauncher/Collapse/assets/63875873/fe0d9d4e-65f2-4ad5-9582-70501aa09d78)
![image](https://github.com/CollapseLauncher/Collapse/assets/63875873/9d2b44db-0f3c-4098-a2fd-d0bd2df8944c)

**Comment by Bloo-561** [comment]
System.TypeLoadException: Failed while trying to load Metadata Stamp!
 ---> System.Text.Json.JsonException: DeserializeUnableToConvertValue, System.Nullable`1[CollapseLauncher.Helper.Metadata.MetadataType] Path: $[15].MetadataType | LineNumber: 137 | BytePositionInLine: 36.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String )
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader&, Type, JsonSerializerOptions)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader&, Type, JsonSerializerOptions)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& , Boolean& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack&)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState&, JsonReaderState&, ReadStack&)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream, CancellationToken)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream, CancellationToken)
   at CollapseLauncher.JSONSerializerHelper.InnerDeserializeStreamAsync[T](Stream data, JsonSerializerContext context, CancellationToken token, T defaultType)
   at CollapseLauncher.JSONSerializerHelper.DeserializeAsync[T](Stream data, JsonSerializerContext context, CancellationToken token, T defaultType)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeStamp(String currentChannel, Boolean throwAfterRetry)
   Exception_EndOfInnerExceptionStack
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeStamp(String currentChannel, Boolean throwAfterRetry)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeStamp(String currentChannel, Boolean throwAfterRetry)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeStamp(String currentChannel, Boolean throwAfterRetry)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeStamp(String currentChannel, Boolean throwAfterRetry)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.Initialize(Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.MainPage.InitializeStartup()
   at CollapseLauncher.MainPage.StartRoutine(Object sender, RoutedEventArgs e)

**Comment by bagusnl** [comment]
Hi, can you inform us what Windows language and locale you are using?

**Comment by Bloo-561** [comment]
> Hi, can you inform us what Windows language and locale you are using?

EN-US

**Comment by bagusnl** [comment]
Can you try running this build (just extract and run CollapseLauncher.exe) and see if its still does the same thing https://nightly.link/CollapseLauncher/Collapse/actions/runs/9927743923

**Comment by Bloo-561** [comment]
![image](https://github.com/user-attachments/assets/8f9c6575-824a-4a45-85cb-79a3e95edb6b)
System.Collections.Generic.KeyNotFoundException: Arg_KeyNotFoundWithKey, 1417707373
   at System.Collections.Generic.Dictionary`2.get_Item(TKey)
   at CollapseLauncher.Statics.GamePropertyVault.GetCurrentGameProperty()
   at CollapseLauncher.Pages.HomePage.StartLoadedRoutine(Object sender, RoutedEventArgs e)
   
   And yes im connected

**Comment by bagusnl** [comment]
go to other region via the selector, go to app settings, then on the right panel press "Clear Metadata and Restart"

**Comment by Bloo-561** [comment]
That did the trick, that's weird but hey it works

**Comment by bagusnl** [comment]
probably last time it tries to update the metadata it gets interrupted somehow

**Comment by Bloo-561** [comment]
Ah okay, thanks for your help.
