### ISSUE TITLE
[Bug]: 原神4.8版本预下载包体无法下载|Genshin Impact 4.8 version pre-download package cannot be downloaded

### ISSUE THREAD

**Issue by qinglangchaoke** [CollapseLauncher/Collapse#534]
### Affected Version

1.80.15 Stable

### Bug Behavior

在下载的时候，会弹出错误窗口|When downloading, an error window will pop up
错误代码|Error codes：
System.NullReferenceException: Url returns an empty/null data!
   at Hi3Helper.Sophon.SophonManifest.CreateSophonChunkManifestInfoPair(HttpClient, String, String, CancellationToken)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.AddSophonDiffAssetsToList(HttpClient httpClient, String requestedUrlFrom, String requestedUrlTo, List`1 sophonPreloadAssetList, String matchingField)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.PredownloadDialog(Object sender, RoutedEventArgs e)

### Expected Behavior

希望告诉我这是怎么发生的，怎么修复|Hope to tell me how this happened and how to fix it

### Steps to reproduce

点击预下载后就会弹出错误窗口|After clicking on the pre-download, an error window will pop up

### Screenshot(s)

![QQ_1721017720881](https://github.com/user-attachments/assets/9564291d-a53f-4ea9-a94d-10c95d541eed)

**Comment by bagusnl** [comment]
Go to Collapse settings, scroll down and do "Clear Metadata and Restart"

**Comment by bagusnl** [comment]
Fixed in Stable and Preview
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3
