### ISSUE TITLE
[Bug]: Genshin Impact 4.7 --> 4.8 update

### ISSUE THREAD

**Issue by KK5C** [CollapseLauncher/Collapse#542]
### Affected Version

1.80.16

### Bug Behavior

Gets a few seconds into update process before spitting out error code.

### Expected Behavior

Game update

### Steps to reproduce

1) Installed Launcher
2) Chose Genshin (global)
3) Locate Direcetory  `C:\Program Files\Genshin Impact\Genshin Impact game`
4) Attempt update from existing Genshin 4.7 install
5) Error code

### Additional Information

```
System.UnauthorizedAccessException: UnauthorizedAccess_IODenied_Path, C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact_Data\Plugins\ThirdPartyNotices.txt
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String, FileMode, FileAccess, FileShare, FileOptions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.SyncWindowsFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream, String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions, Int64)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, FileOptions)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, Boolean)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare)
   at System.IO.FileInfo.Open(FileMode, FileAccess, FileShare)
   at Hi3Helper.Sophon.SophonAsset.InnerWriteUpdateAsync(HttpClient, String, DelegateReadStreamInfo, FileInfo, FileInfo, SophonChunk, Boolean, CancellationToken)
   at Hi3Helper.Sophon.SophonAsset.InnerWriteUpdateAsync(HttpClient, String, DelegateReadStreamInfo, FileInfo, FileInfo, SophonChunk, Boolean, CancellationToken)
   at Hi3Helper.Sophon.SophonAsset.<>c__DisplayClass39_0.<<WriteUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Hi3Helper.Sophon.SophonAsset.WriteUpdateAsync(HttpClient, String, String, String, Boolean , ParallelOptions , DelegateReadStreamInfo , DelegateDownloadAssetComplete )
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<>c__DisplayClass93_0.<<StartPackageUpdateSophon>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

```

Log file comes from `C:\Users\%username%\AppData\LocalLow\CollapseLauncher\GameFolder\_logs` as `C:\Users\%username%\AppData\LocalLow\CollapseLauncher\_logs` does not exist

[DxDiag.txt](https://github.com/user-attachments/files/16289810/DxDiag.txt)
[log-2024-07-18-sta1.80.16-id0.log](https://github.com/user-attachments/files/16289926/log-2024-07-18-sta1.80.16-id0.log)

**Comment by bagusnl** [comment]
Hi~
This has been fixed in the dev version, you can try it out using this link here

 https://github.com/CollapseLauncher/Collapse/actions/runs/9975958014

Download the artifact, extract, and run CollapseLauncher directly from the extracted folder

**Comment by KK5C** [comment]
Oh, should have looked at other issues closer. Thank you!

**Comment by bagusnl** [comment]
Should be fixed both in Stable and Preview
If you still have problem, reopen this ticket or open another one.

Thanks for the support <3
