### ISSUE TITLE
[Bug]：缓存更新出现错误|Error in cache update

### ISSUE THREAD

**Issue by 13read-Github** [CollapseLauncher/Collapse#543]
### Affected Version

Collapse 1.80.16

### Bug Behavior

在我手动更新缓存时，发生了报错(快速检查)|An error emerged during my manual update of the cache (quick check)：
[Erro]   [16:30:06.690]  An error occured while checking cache!
System.IO.InvalidDataException: The dispatcher response is invalid! Please open an issue to our GitHub page to report this issue.
   at CollapseLauncher.StarRailCache.Fetch(CancellationToken token)
   at CollapseLauncher.StarRailCache.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`1.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailCache.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.CachesPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

使用完整检查时，又出现了报错|An error occurred again when using the full check.：
System.IO.InvalidDataException: The dispatcher response is invalid! Please open an issue to our GitHub page to report this issue.
   at CollapseLauncher.StarRailCache.Fetch(CancellationToken token)
   at CollapseLauncher.StarRailCache.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`1.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.StarRailCache.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.CachesPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

### Expected Behavior

提供解决方案或查找错误原因|Provide a solution or find the cause of the error

### Steps to reproduce

无法表述|Unable to be expressed

**Comment by bagusnl** [comment]
Cannot replicate issue, please check your internet connection and try again

**Comment by bagusnl** [comment]
Cannot reproduce + stale ticket

Please reopen this ticket once you confirm you still get the bug in new version of Collapse
