### ISSUE TITLE
[Bug]: Unhandled Error: System.IndexOutOfRangeException: Arg_IndexOutOfRangeException

### ISSUE THREAD

**Issue by nawka12** [CollapseLauncher/Collapse#553]
### Affected Version

Collapse 1.81.0-PRE

### Bug Behavior

Bug preventing me to install Zenless Zone Zero and spitting this error after choosing directory:
```
System.IndexOutOfRangeException: Arg_IndexOutOfRangeException
   at Hi3Helper.Data.HexTool.BytesToHexUnsafe(ReadOnlySpan`1)
   at CollapseLauncher.InstallManager.GameInstallPackage.get_HashString()
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.AddMainResourceVersionList(RegionResourceVersion asset, List`1 packageList, Boolean isSkipMainPackage)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.TryAddResourceVersionList(RegionResourceVersion asset, List`1 packageList, Boolean isSkipMainPackage)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.GetLatestPackageList(List`1 packageList, GameInstallStateEnum gameState, Boolean usePreload)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e)
```

### Expected Behavior

It should start downloading the assets file of the game.

### Steps to reproduce

1. Open Collapse
2. Choose ZZZ Global
3. Install/Locate game, locate directory or use default directory.
4. The error code show up.

### Screenshot(s)

![image](https://github.com/user-attachments/assets/60851f08-fa63-410e-9d38-3de2b052b87f)

### Additional Information

The reason I'm trying to use 1.81.0-PRE is because the I keep having hash mismatch issue on 1.80.17.

**Comment by neon-nyan** [comment]
We have pushed a commit to fix the issue and should be expected to get shipped in the next preview version.
https://github.com/CollapseLauncher/Collapse/commit/d0a0941d6949ebdd2c0c1adcef01b933b48fbc99

**Comment by nawka12** [comment]
Thank you.

Is there any way I can get this fix early ~~without building it myself~~?

**Comment by bagusnl** [comment]
Use latest build from our CI https://github.com/CollapseLauncher/Collapse/actions/workflows/build.yml

just extract and run, do not overwrite your current collapse installation
we are hoping to push next preview tonight

**Comment by nawka12** [comment]
Thank you!
