### ISSUE TITLE
[Bug]: Manifest for Mainland China (version: 7.7.0) doesn't exist!

### ISSUE THREAD

**Issue by cocochick** [CollapseLauncher/Collapse#554]
### Affected Version

1.81.1 preview

### Bug Behavior

Game repair failed, error is below
System.Data.VersionNotFoundException: Manifest for Mainland China (version: 7.7.0) doesn't exist! Please contact @neon-nyan or open an issue for this!
   at CollapseLauncher.HonkaiRepair.Fetch(List`1 assetIndex, CancellationToken token)
   at CollapseLauncher.HonkaiRepair.CheckRoutine()
   at CollapseLauncher.Interfaces.ProgressBase`1.TryRunExamineThrow(Task`1 action)
   at CollapseLauncher.HonkaiRepair.StartCheckRoutine(Boolean useFastCheck)
   at CollapseLauncher.Pages.RepairPage.RunCheckRoutine(Object sender, Boolean isFast, Boolean isMainButton)

### Expected Behavior

start checking files

### Steps to reproduce

1. switch Mainland China for Honkai3
2. use game repair
3. start a quick check

**Comment by neon-nyan** [comment]
Hi there,
Sorry for my very late response.
This issue should have been fixed as the metadata and the necessary asset indexes have been updated as well.

Closing this issue for now
