### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Leo-de-Z** [CollapseLauncher/Collapse#566]
### Affected Version

1.80.19

### Bug Behavior

launcher not initializing

### Expected Behavior

intitialize

### Steps to reproduce

Not sure just opening the launcher

### Additional Information

System.TypeLoadException: Failed while trying to load Metadata Config for: Zenless Zone Zero - Bilibili!
 ---> System.TimeoutException: All available CDNs aren't reachable for your network while getting content: /metadata/v3/stable/config_ZZZBilibili.json. Please check your internet!
   at CollapseLauncher.FallbackCDNUtil.TryGetCDNFallbackStream(String relativeURL, CancellationToken token, Boolean isForceUncompressRequest)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   Exception_EndOfInnerExceptionStack
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeConfig(String currentChannel, Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.Initialize(Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.MainPage.InitializeStartup()
   at CollapseLauncher.MainPage.StartRoutine(Object sender, RoutedEventArgs e)

**Comment by gingingin100** [comment]
Same problem here

**Comment by Lounode** [comment]
same
```
System.TypeLoadException: Failed while trying to load Metadata Config for: Zenless Zone Zero - Bilibili!
 ---> System.TimeoutException: All available CDNs aren't reachable for your network while getting content: /metadata/v3/stable/config_ZZZBilibili.json. Please check your internet!
   at CollapseLauncher.FallbackCDNUtil.TryGetCDNFallbackStream(String relativeURL, CancellationToken token, Boolean isForceUncompressRequest)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   Exception_EndOfInnerExceptionStack
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeConfig(String currentChannel, Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.Initialize(Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.MainPage.InitializeStartup()
   at CollapseLauncher.MainPage.StartRoutine(Object sender, RoutedEventArgs e)
```

**Comment by NyaShinn1204** [comment]
same problem
```
System.TypeLoadException: Failed while trying to load Metadata Config for: Zenless Zone Zero - Bilibili!
 ---> System.TimeoutException: All available CDNs aren't reachable for your network while getting content: /metadata/v3/stable/config_ZZZBilibili.json. Please check your internet!
   at CollapseLauncher.FallbackCDNUtil.TryGetCDNFallbackStream(String relativeURL, CancellationToken token, Boolean isForceUncompressRequest)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   Exception_EndOfInnerExceptionStack
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.LoadConfigInner(Stamp stamp, String currentChannel, Boolean throwAfterRetry, Boolean allowDeserializeKey, Boolean isCacheUpdateModeOnly)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.InitializeConfig(String currentChannel, Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.Helper.Metadata.LauncherMetadataHelper.Initialize(Boolean isCacheUpdateModeOnly, Boolean isShowLoadingMessage)
   at CollapseLauncher.MainPage.InitializeStartup()
   at CollapseLauncher.MainPage.StartRoutine(Object sender, RoutedEventArgs e)
   ```

**Comment by Cryotechnic** [comment]
Hi, please be aware that due to the new Genshin 5.0 update, HoYoverse's CDN is experiencing a period of extreme load, which causes instability. Everything currently works as intended from our infrastructure's point of view. If you cannot load into the region, please try to launch the game by manually navigating to the game installation folder. You can do so by clicking on the "Quick Settings" button and clicking on "Open Game Folder".

![image](https://github.com/user-attachments/assets/a94c2ad4-dc6d-4e57-ac31-f45a745c7893)

We apologize for the inconvenience we may have caused and thank you for your patience. If the issue persists tomorrow or in a couple of days, feel free to send an updated response here.

**Comment by lotgood** [comment]
> Hi, please be aware that due to the new Genshin 5.0 update, HoYoverse's CDN is experiencing a period of extreme load, which causes instability. Everything currently works as intended from our infrastructure's point of view. If you cannot load into the region, please try to launch the game by manually navigating to the game installation folder. You can do so by clicking on the "Quick Settings" button and clicking on "Open Game Folder".
> 
> ![image](https://private-user-images.githubusercontent.com/9833218/362035564-a94c2ad4-dc6d-4e57-ac31-f45a745c7893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDU5NzMsIm5iZiI6MTcyNDgwNTY3MywicGF0aCI6Ii85ODMzMjE4LzM2MjAzNTU2NC1hOTRjMmFkNC1kYzZkLTRlNTctYWMzMS1mNDVhNzQ1Yzc4OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDA0MTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAyMTVjODEzODIyYTllZjM1Y2RlNTA3ZjY1MjJmMmVlMDlkNjE2YmU2MzA5NmM4NTEyZjZlMTc1NzA3NzhmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tDZjSiXnL0LXIw3_vZs-gcufedjUVwKp1005OvmMD00)
> 
> We apologize for the inconvenience we may have caused and thank you for your patience. If the issue persists tomorrow or in a couple of days, feel free to send an updated response here.
> 
> Edit: You can try to remediate the issue by clearing the metadata and forcing a launcher restart, through App Settings.

Nothing in the launcher works for me when I run the game from the path, is there any other solution?

**Comment by Cryotechnic** [comment]
> > Hi, please be aware that due to the new Genshin 5.0 update, HoYoverse's CDN is experiencing a period of extreme load, which causes instability. Everything currently works as intended from our infrastructure's point of view. If you cannot load into the region, please try to launch the game by manually navigating to the game installation folder. You can do so by clicking on the "Quick Settings" button and clicking on "Open Game Folder".
> > ![image](https://private-user-images.githubusercontent.com/9833218/362035564-a94c2ad4-dc6d-4e57-ac31-f45a745c7893.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDU5NzMsIm5iZiI6MTcyNDgwNTY3MywicGF0aCI6Ii85ODMzMjE4LzM2MjAzNTU2NC1hOTRjMmFkNC1kYzZkLTRlNTctYWMzMS1mNDVhNzQ1Yzc4OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDA0MTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDAyMTVjODEzODIyYTllZjM1Y2RlNTA3ZjY1MjJmMmVlMDlkNjE2YmU2MzA5NmM4NTEyZjZlMTc1NzA3NzhmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tDZjSiXnL0LXIw3_vZs-gcufedjUVwKp1005OvmMD00)
> > We apologize for the inconvenience we may have caused and thank you for your patience. If the issue persists tomorrow or in a couple of days, feel free to send an updated response here.
> > Edit: You can try to remediate the issue by clearing the metadata and forcing a launcher restart, through App Settings.
> 
> Nothing in the launcher works for me when I run the game from the path, is there any other solution?

We've pushed a metadata update to stable, which should hopefully resolve the issue. Please restart your launcher to receive.

**Comment by ceiler-ovo** [comment]
itworks，thanks!
