### ISSUE TITLE
[Bug]: Using Delta Patch to update the game fails

### ISSUE THREAD

**Issue by Caelum008** [CollapseLauncher/Collapse#571]
### Affected Version

1.81.4

### Bug Behavior

When clicking update, it says I need to fix 114.9 worth of files, upon clicking it, the download will go to around  405MB and then this Unhandled error will appear. Then it will say that the Delta Patch failed to apply.

System.IO.FileNotFoundException: IO_FileNotFound_FileName, C:\Users\████\AppData\LocalLow\CollapseLauncher\GameFolder\Hi3SEA\Games_Ingredients\BH3_Data\StreamingAssets\Asb\pc\2f23e99b475dc84b1a13fbe27eec3db4.wmv
IO_FileName_Name, C:\Users\████\AppData\LocalLow\CollapseLauncher\GameFolder\Hi3SEA\Games_Ingredients\BH3_Data\StreamingAssets\Asb\pc\2f23e99b475dc84b1a13fbe27eec3db4.wmv
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.File.Open(String, FileMode, FileAccess, FileShare)
   at SharpHDiffPatch.Core.Patch.PatchDir.GetRefOldStreams(DirectoryReferencePair)
   at SharpHDiffPatch.Core.Patch.PatchDir.Patch(String, String, Boolean, Boolean, Boolean)
   at SharpHDiffPatch.Core.HDiffPatch.Patch(String, String, Boolean, CancellationToken , Boolean , Boolean )
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.<>c__DisplayClass89_0.<StartDeltaPatch>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartDeltaPatch(IRepairAssetIndex repairGame, Boolean isHonkai, Boolean isSR)
   at CollapseLauncher.InstallManager.Honkai.HonkaiInstall.StartPackageInstallationInner(List`1 gamePackage, Boolean isOnlyInstallPackage, Boolean doNotDeleteZipExplicit)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase.StartPackageInstallation()
   at CollapseLauncher.Pages.HomePage.UpdateGameDialog(Object sender, RoutedEventArgs e)

### Expected Behavior

Should update without a problem.

### Steps to reproduce

1. Restarted Collapse
2. Tried changing to Stable release

**Comment by bagusnl** [comment]
This is known for Global version, @neon-nyan will investigate it in a bit

**Comment by bagusnl** [comment]
Well, I guess SEA too :derp:
