### ISSUE TITLE
[Bug]: Crashing "style preferences" on startup configuration

### ISSUE THREAD

**Issue by IRedDragonICY** [CollapseLauncher/Collapse#578]
### Affected Version

1.81.5 Preview

### Bug Behavior

```
FATAL ERROR ON APP MAIN() LEVEL AND THE MAIN THREAD HAS BEEN TERMINATED!!!
System.InvalidCastException: Arg_InvalidCastException
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32)
   at ABI.Microsoft.UI.Xaml.Controls.IStyleSelectorMethods.SelectStyle(IObjectReference, Object, DependencyObject)
   at Microsoft.UI.Xaml.Controls.StyleSelector.SelectStyle(Object, DependencyObject)
   at CommunityToolkit.WinUI.Controls.SettingsExpander.ItemsRepeater_ElementPrepared(ItemsRepeater sender, ItemsRepeaterElementPreparedEventArgs args)
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Microsoft_UI_Xaml_Controls_ItemsRepeater__global__Microsoft_UI_Xaml_Controls_ItemsRepeaterElementPreparedEventArgs_.EventState.<GetEventInvoke>b__1_0(ItemsRepeater sender, ItemsRepeaterElementPreparedEventArgs args)
   at WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Microsoft_UI_Xaml_Controls_ItemsRepeater__Microsoft_UI_Xaml_Controls_ItemsRepeaterElementPreparedEventArgs.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr args)

If you are sure that this is not intended, please report it to: https://github.com/CollapseLauncher/Collapse/issues
Press any key to exit or Press 'R' to restart the main thread app...
```

### Expected Behavior

missing style preference

### Steps to reproduce

1. Click style preference dropdown
2. Crashes 

### Screenshot(s)

![image](https://github.com/user-attachments/assets/6b9c7c2b-2aff-4718-b049-5e84b33a14af)

![image](https://github.com/user-attachments/assets/83172b9e-df7e-435f-af2d-b26547f750ad)

**Comment by bagusnl** [comment]
Fixed in `net-9` branch #577, changes cannot be backported (easily) due to the complexity of the changes needed to fix everything inside the OOBE.
Still waiting for rc2 of .NET9 to be able to push the branch to preview release due to critical bug in the runtime
