### ISSUE TITLE
[Bug]: Crash when launching game.

### ISSUE THREAD

**Issue by Pliexe** [CollapseLauncher/Collapse#580]
### Affected Version

1.81.6 Preview

### Bug Behavior

When any of the games are launched the launcher crashes and prints an error in the console.

### Expected Behavior

The launcher shouldn't have crashed when starting the game, but have either minimized or stay open depending on how it's configured.

### Steps to reproduce

1. Start launcher 
2. On any game click "Start Game" button

### Screenshot(s)

![image](https://github.com/user-attachments/assets/34163ae8-4a9f-4487-82fb-0e35f4dba7a2)

### Additional Information

FATAL ERROR ON APP MAIN() LEVEL AND THE MAIN THREAD HAS BEEN TERMINATED!!!
System.Runtime.InteropServices.COMException (0x80070001): No such interface supported

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32)
   at H.NotifyIcon.Interop.InteropUtilities.EnsureNonZero(BOOL)
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetProcessQualityOfServiceLevel(QualityOfServiceLevel)
   at H.NotifyIcon.EfficiencyMode.EfficiencyModeUtilities.SetEfficiencyMode(Boolean)
   at H.NotifyIcon.WindowExtensions.Hide(Window, Boolean )
   at CollapseLauncher.TrayIcon.ToggleMainVisibility(Boolean forceShow)
   at CollapseLauncher.Helper.WindowUtility.ToggleToTray_MainWindow()
   at CollapseLauncher.Pages.HomePage.StartGame(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

If you are sure that this is not intended, please report it to: https://github.com/CollapseLauncher/Collapse/issues
Press any key to exit or Press 'R' to restart the main thread app...

**Comment by bagusnl** [comment]
What version of windows are you on?

**Comment by bagusnl** [comment]
Also for workaround, try setting the after game launch behavior to "minimize" or "nothing" for now

**Comment by bagusnl** [comment]
Also for workaround, try setting the after game launch behavior to "minimize" or "nothing" for now

**Comment by Pliexe** [comment]
> What version of windows are you on?
Windows 11 23H2 22631.4037

**Comment by bagusnl** [comment]
is the Windows installation modified in any way? like custom ISO or tweak script?

I can't replicate it on my end in 24H2

**Comment by Pliexe** [comment]
> is the Windows installation modified in any way? like custom ISO or tweak script?
> 
> I can't replicate it on my end in 24H2

If you mean by manually removing parts such as apps, or disabling some stuff in the registry, yes it is.

**Comment by bagusnl** [comment]
I will try to make the method not crashing the entire app, but essentially the failing code is the one that calls for Collapse to be put on "Efficiency Mode" so that it won't take much if any CPU in the background
