### ISSUE TITLE
[Bug]: Crush while downloading pre-Installation files (Genshin Impact)

### ISSUE THREAD

**Issue by Devyatyi9** [CollapseLauncher/Collapse#589]
### Affected Version

1.80.19

### Bug Behavior

Pre-download error:
`An error occurred while starting preload process: System.IO.IOException: IO_SharingViolation_File, E:\Games\Genshin Impact Game\chunk_collapse\f21e1b2f432ec11c84513b3543c736d7.verified`
<details><summary>The error</summary>

```
System.IO.IOException: IO_SharingViolation_File, E:\Games\Genshin Impact Game\chunk_collapse\f21e1b2f432ec11c84513b3543c736d7.verified
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String, FileMode, FileAccess, FileShare, FileOptions, Int64, Nullable`1)
   at System.IO.FileStream..ctor(String, FileMode, FileAccess, FileShare, Int32, Boolean)
   at Hi3Helper.Sophon.SophonAsset.PerformWriteDiffChunksThreadAsync(HttpClient, String, SophonChunk, CancellationToken , DelegateWriteStreamInfo , DelegateWriteDownloadInfo , Boolean )
   at Hi3Helper.Sophon.SophonAsset.<>c__DisplayClass3_0.<<DownloadDiffChunksAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Hi3Helper.Sophon.SophonAsset.DownloadDiffChunksAsync(HttpClient, String, ParallelOptions , DelegateWriteStreamInfo , DelegateWriteDownloadInfo , DelegateDownloadAssetComplete , Boolean )
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.<>c__DisplayClass97_0.<<StartPackageUpdateSophon>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__53`1.<<ForEachAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location ---
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageUpdateSophon(GameInstallStateEnum gameState, Boolean isPreloadMode)
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog)
   at CollapseLauncher.Pages.HomePage.PredownloadDialog(Object sender, RoutedEventArgs e)
```

</details>

### Expected Behavior

It should download game files

### Steps to reproduce

Pre-download Genshin Impact 5.1

### Additional Information

[log-2024-10-07-sta1.80.19-id0.log](https://github.com/user-attachments/files/17287929/log-2024-10-07-sta1.80.19-id0.log)
[log-2024-10-08-sta1.80.19-id0.log](https://github.com/user-attachments/files/17287932/log-2024-10-08-sta1.80.19-id0.log)

**Comment by neon-nyan** [comment]
Hi there, currently there's some issue with Sophon module on stable release.
I would recommend you to switch to preview release for downloading the preload
