### ISSUE TITLE
[Bug]: Buffer insufficient on 24h2

### ISSUE THREAD

**Issue by sino1641** [CollapseLauncher/Collapse#594]
### Affected Version

 Collapse Launcher [1.81.6]

### Bug Behavior

```
[Schm]    Initializing Region HI3 (Mainland China) Done!
[Warn]    Buffer requested is insufficient! Requested: 745992 > Capacity: 524288, Resizing the buffer...
[Erro]    [XAML_OTHER] Sender: CollapseLauncher.App
System.Runtime.InteropServices.COMException (0x80004005)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference, Size)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
FATAL ERROR ON APP MAIN() LEVEL AND THE MAIN THREAD HAS BEEN TERMINATED!!!
System.Runtime.InteropServices.COMException (0x80004005)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference, Size)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)

If you are sure that this is not intended, please report it to: https://github.com/CollapseLauncher/Collapse/issues
Press any key to exit or Press 'R' to restart the main thread app...
```
Hi,
There is an error saying Buffer requested is insufficient! on 24h2.
When I press R or restart the app, it works as normal.

### Expected Behavior

No error

### Steps to reproduce

1. Install windows 11 24h2
2. Open Collapse

**Comment by bagusnl** [comment]
This is not buffer issue, but WinUI issue
Should be fixed on next preview release, for now just press R to restart the launcher or restart it manually. 
Related to #585 

Unless its reproducible consistently, then we're talking
